version: '3.8'

services:
  websocket:
    build:
      context: .  # Directorio donde se encuentra el Dockerfile del WebSocket
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=production